### ISSUE TITLE
phyton error

### ISSUE THREAD

**Issue by Madikydiseno** [LorenzWieseke/GLBTextureTools#4]
Hello, I am having this error, which prevents me from using the addon.
Python: Traceback (most recent call last):
  File "C:\Users\Raquel\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GLBTextureTools\Operators\bake_operator.py", line 46, in execute
    bake_manager.bake_texture(self,selected_objects,bake_settings)
  File "C:\Users\Raquel\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GLBTextureTools\Bake\bake_manager.py", line 30, in bake_texture
    lightmap_utilities.add_node_setup()
  File "C:\Users\Raquel\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GLBTextureTools\Bake\bake_utilities.py", line 238, in add_node_setup
    self.position_gltf_setup_nodes(material,uv_node,image_texture_node,gltf_settings_node)
  File "C:\Users\Raquel\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\GLBTextureTools\Bake\bake_utilities.py", line 216, in position_gltf_setup_nodes
    loc = pbr_node.location + pos_offset
 AttributeError: 'NoneType' object has no attribute 'location'

blender version 3.2.2 and addon version 0.1.3
how can I solve that?
Thanks in advance

**Comment by LorenzWieseke** [comment]
Please check if there is a Principled BSDF node in your material.The add-on only works with PBR materials since this is the current standard. 

I add some extra notification for the user. Also I made a script to convert other node setups to pbr nodes, just didn't have the time to integrate it yet

**Comment by Madikydiseno** [comment]
Thanks! goovie updated its exporter to version 1.4 and part of the error has been resolved.
I would love to receive that update. to convert to pbr material
