### ISSUE TITLE
bug disapear~!!blender3.6.

### ISSUE THREAD

**Issue by suicaoya123** [LorenzWieseke/GLBTextureTools#5]
Python: Traceback (most recent call last):
  File "C:\Users\zzz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GLBTextureTools\Panels\panel_ui_list.py", line 50, in filter_items
    [images.append(node.image.name) for node in tex_nodes]
  File "C:\Users\zzz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GLBTextureTools\Panels\panel_ui_list.py", line 50, in <listcomp>
    [images.append(node.image.name) for node in tex_nodes]
AttributeError: 'NoneType' object has no attribute 'name'
Location: C:\Users\zzz\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\GLBTextureTools\Panels\panel.py:175

is there any discord group ?

**Comment by LorenzWieseke** [comment]
You can write me directly on:
https://discord.gg/AyHpxtb7b3
