### ISSUE TITLE
Blender 4.1 Support?

### ISSUE THREAD

**Issue by sweco-sekrsv** [LorenzWieseke/GLBTextureTools#8]
Hi!

I just tried the tool under Blender 4.1 and it does not work, I get the following error:

```
Python: Traceback (most recent call last):
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Operators\bake_operator.py", line 46, in execute
    bake_manager.bake_texture(self,selected_objects,bake_settings)
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Bake\bake_manager.py", line 32, in bake_texture
    lightmap_utilities.add_node_setup()
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Bake\bake_utilities.py", line 271, in add_node_setup
    image_texture_node = self.add_image_texture_node(material)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Bake\bake_utilities.py", line 208, in add_image_texture_node
    self.bake_image.colorspace_settings.name = "Linear"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: bpy_struct: item.attr = val: enum "Linear" not found in ('ACES2065-1', 'ACEScg', 'AgX Base Display P3', 'AgX Base Rec.1886', 'AgX Base Rec.2020', 'AgX Base sRGB', 'AgX Log', 'Display P3', 'Filmic Log', 'Filmic sRGB', 'Linear CIE-XYZ D65', 'Linear CIE-XYZ E', 'Linear DCI-P3 D65', 'Linear FilmLight E-Gamut', 'Linear Rec.2020', 'Linear Rec.709', 'Non-Color', 'Rec.1886', 'Rec.2020', 'sRGB')
```

I tried fixing that adding:
self.bake_image.colorspace_settings.name = "Linear Rec.709"

Then I ran into the next problem:

```
Python: Traceback (most recent call last):
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Operators\bake_operator.py", line 46, in execute
    bake_manager.bake_texture(self,selected_objects,bake_settings)
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Bake\bake_manager.py", line 32, in bake_texture
    lightmap_utilities.add_node_setup()
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Bake\bake_utilities.py", line 278, in add_node_setup
    gltf_settings_node = self.add_gltf_material_output_node(material)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sekrsv\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\GLBTextureTools\Bake\bake_utilities.py", line 153, in add_gltf_material_output_node
    gltf_node_group.inputs.new("NodeSocketFloat", "Occlusion")
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ShaderNodeTree' object has no attribute 'inputs'
```

Do you have plans to test it for Blender 4.1 and release a new version?

**Comment by LorenzWieseke** [comment]
The problem is that they changed the whole principled shader and I would need to do a complete redesign.

Also the baking wasn't ideal, you could try simple bake instead for the time being...

⁣Mit freundlichen Grüßen, Lorenz Wieseke​
